apiVersion: v2
name: ascent-mongodb
description: NoSQL document-oriented database that stores JSON-like documents with dynamic schemas, simplifying the integration of data in content-driven applications.
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
annotations:
  category: Database
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  tags:
  - mongodb
  version: 10.27.2
